name: Deploy Backend 
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/DockerFile.backend
          push: true
          tags: kanurag0/appxbuild:${{github.sha}}
      - name: Deploy to VM 
        run: |
          echo "${{ secrets.SSH_KEY }}" &> ~ssh_key
          ls /home/runner/.ssh
          mkdir -p /home/runner/.ssh
          chmod 700 /home/runner/ssh_key
          ssh -0 StrictHostKeyChecking=no -i ~ssh_key ubuntu@54.234.24.224


