name: Deploy Frontend 

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker Image
        run: |
          docker build -f ./docker/DockerFile.frontend -e ${{ secrets.DATABASE_URL }} --build-arg DATABASE_URL=${{ secrets.DATABASE_URL }} -t kanurag0/appxfrontend:${{github.sha}} . 
          docker push kanurag0/appxfrontend:${{ github.sha }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.234.24.224 >> ~/.ssh/known_hosts

      - name: Deploy to VM 
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@54.234.24.224 "docker images prune -a --force && docker pull kanurag0/appxfrontend:${{ github.sha }} && docker run -d --name app-fr -e DATABASE_URL=${{ secrets.DATABASE_URL }} kanurag0/appxfrontend:${{ github.sha }}"
